#!/bin/sh

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
	if [ "develop" == "$branch" ]; then
		echo "Develop. Jenkins not setup yet. Refer to jenkins build notebook for instructions."
	elif [ "master" == "$branch" ]; then
		echo "Master. Sending triggerto jenkins."
	 curl -u jin:11cf2ecf36c8458239763fb4d6644110e8 https://jenkins.jinis.online/job/blog-master/build?token=gjeirsa4398gs
	fi

done

exit 0
